steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - ${_CACHE_IMAGE}
    allowFailure: true
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - ${_CACHE_IMAGE}
      - --file
      - api/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
